### ISSUE TITLE
Any meeting feedback?

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimistic-pm#4]
**Background**
Last call we discussed creating an issue where we can discuss call meta and improvements.

Please leave any comments or suggestions here! 😊

**Comment by lightclient** [comment]
Two main points of feedback:

1. I recommend posting call info as an issue `ethereum/pm` instead of this repo. That is the canonical location for "protocol" call information. Anyone is free to post there, we've published a few calls there for AA and EIP-3074 without the EF.
2. All "core" Ethereum calls are hosted via Zoom. This is a small thing, but I think if you want to create a similar environment to ACD and other protocol calls, this will help create a more familiar environment.

**Comment by karlfloersch** [comment]
> I recommend posting call info as an issue ethereum/pm...All "core" Ethereum calls are hosted via Zoom.

Oh interesting! @smartcontracts suggested we put the meeting notes as issues in the specs repo, so seems like we've got a bunch of different opinions here. I am super un-opinionated about where information lives as long as it lives somewhere. And it's important that it the home doesn't move too much.
